### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by ma-karai** [plugsy/core#13]
```
6/28/2021 8:23:28 AMinfo:    ┏ > Server listening at http://localhost:3000 as production +2ms
6/28/2021 8:23:28 AMinfo:    ┗ [1] { component: 'startServer' }
6/28/2021 8:23:40 AMApolloError: request to https://192.168.0.32:3000/graphql failed, reason: write EPROTO 140530077128512:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
6/28/2021 8:23:40 AM
6/28/2021 8:23:40 AM    at new ApolloError (/home/node/node_modules/@apollo/client/errors/errors.cjs.js:31:28)
6/28/2021 8:23:40 AM    at /home/node/node_modules/@apollo/client/core/core.cjs.js:1493:19
6/28/2021 8:23:40 AM    at both (/home/node/node_modules/@apollo/client/utilities/utilities.cjs.js:963:53)
6/28/2021 8:23:40 AM    at /home/node/node_modules/@apollo/client/utilities/utilities.cjs.js:956:72
6/28/2021 8:23:40 AM    at new Promise (<anonymous>)
6/28/2021 8:23:40 AM    at Object.then (/home/node/node_modules/@apollo/client/utilities/utilities.cjs.js:956:24)
6/28/2021 8:23:40 AM    at Object.error (/home/node/node_modules/@apollo/client/utilities/utilities.cjs.js:964:49)
6/28/2021 8:23:40 AM    at notifySubscription (/home/node/node_modules/zen-observable/lib/Observable.js:140:18)
6/28/2021 8:23:40 AM    at onNotify (/home/node/node_modules/zen-observable/lib/Observable.js:179:3)
6/28/2021 8:23:40 AM    at SubscriptionObserver.error (/home/node/node_modules/zen-observable/lib/Observable.js:240:7) {
6/28/2021 8:23:40 AM  graphQLErrors: [],
6/28/2021 8:23:40 AM  networkError: FetchError: request to https://192.168.0.32:3000/graphql failed, reason: write EPROTO 140530077128512:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
6/28/2021 8:23:40 AM
6/28/2021 8:23:40 AM      at ClientRequest.<anonymous> (/home/node/node_modules/node-fetch/lib/index.js:1461:11)
6/28/2021 8:23:40 AM      at ClientRequest.emit (events.js:375:28)
6/28/2021 8:23:40 AM      at TLSSocket.socketErrorListener (_http_client.js:475:9)
6/28/2021 8:23:40 AM      at TLSSocket.emit (events.js:375:28)
6/28/2021 8:23:40 AM      at emitErrorNT (internal/streams/destroy.js:106:8)
6/28/2021 8:23:40 AM      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
6/28/2021 8:23:40 AM      at processTicksAndRejections (internal/process/task_queues.js:82:21) {
6/28/2021 8:23:40 AM    type: 'system',
6/28/2021 8:23:40 AM    errno: 'EPROTO',
6/28/2021 8:23:40 AM    code: 'EPROTO'
6/28/2021 8:23:40 AM  },
6/28/2021 8:23:40 AM  extraInfo: undefined
6/28/2021 8:23:40 AM}
```

**Comment by petersem** [comment]
@ma-karai  I was just about to log the same issue. You beat me to it :)

**Comment by Inlustra** [comment]
@ma-karai @petersem Can you please post your config files?

**Comment by petersem** [comment]
@Inlustra I didnt create a config file. Only using some basic yaml in a compose file. 

`  plugsy:
    image: plugsy/core
    container_name: plugsy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    restart: unless-stopped

  wbo:
    image: lovasoa/wbo
    container_name: wbo
    labels:
      dockerDash.category: 'Collaboration'
      dockerDash.name: 'WBO'
      #dockerDash.parents: 'Todo'
      dockerDash.icon: 'fi/FiDatabase'
    ports:
      - 5005:80
    volumes:
      - $PERSIST/wbo:/opt/app/server-data" 
    restart: unless-stopped`

**Comment by Inlustra** [comment]
Awesome, thanks!
Odd, it's definitely trying to use https on your endpoint that is obviously http.

Lemme see if I can replicate!

**Comment by ma-karai** [comment]
> @ma-karai @petersem Can you please post your config files?
> 
> I'm assuming this is in agent mode?
No just plugsy and a a single container

**Comment by petersem** [comment]
> Awesome, thanks!
> Odd, it's definitely trying to use https on your endpoint that is obviously http.
> 
> Lemme see if I can replicate!

My error is the same as @ma-karai 

```
    at SubscriptionObserver.error (/home/node/node_modules/zen-observable/lib/Observable.js:240:7) {

  graphQLErrors: [],

  networkError: FetchError: request to https://192.168.1.135:3000/graphql failed, reason: write EPROTO 139928322590528:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

  

      at ClientRequest.<anonymous> (/home/node/node_modules/node-fetch/lib/index.js:1461:11)

      at ClientRequest.emit (events.js:375:28)

      at TLSSocket.socketErrorListener (_http_client.js:475:9)

      at TLSSocket.emit (events.js:375:28)

      at emitErrorNT (internal/streams/destroy.js:106:8)

      at emitErrorCloseNT (internal/streams/destroy.js:74:3)

      at processTicksAndRejections (internal/process/task_queues.js:82:21) {

    type: 'system',

    errno: 'EPROTO',

    code: 'EPROTO'

  },

  extraInfo: undefined

}
```

**Comment by Inlustra** [comment]
This will be fixed in 3.1.0, apologies, this was due to a library assuming that any request other than localhost would be https, I've since changed it to use the correct protocol.

**Comment by petersem** [comment]
Maybe something to do with the absoluteUrl call in _app.tsx. Being that this is in a container, can it be hardcoded, rather than derived?

**Comment by ma-karai** [comment]
```
6/28/2021 10:32:36 AMError: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
6/28/2021 10:32:36 AM    at a.b.render (/home/node/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:45:32)
6/28/2021 10:32:36 AM    at a.b.read (/home/node/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
6/28/2021 10:32:36 AM    at exports.renderToString (/home/node/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
6/28/2021 10:32:36 AM    at renderPage (/home/node/node_modules/next/dist/next-server/server/render.js:54:854)
6/28/2021 10:32:36 AM    at Object.ctx.renderPage (/home/node/app/.next/server/pages/_document.js:85:30)
6/28/2021 10:32:36 AM    at Function.getInitialProps (/home/node/app/.next/server/chunks/590.js:542:19)
6/28/2021 10:32:36 AM    at Function.getInitialProps (/home/node/app/.next/server/pages/_document.js:89:85)
6/28/2021 10:32:36 AM    at loadGetInitialProps (/home/node/node_modules/next/dist/next-server/lib/utils.js:5:101)
6/28/2021 10:32:36 AM    at renderToHTML (/home/node/node_modules/next/dist/next-server/server/render.js:54:1145)
6/28/2021 10:32:36 AM    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by petersem** [comment]
same
```
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at a.b.render (/home/node/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:45:32)
    at a.b.read (/home/node/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (/home/node/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at renderPage (/home/node/node_modules/next/dist/next-server/server/render.js:54:854)
    at Object.ctx.renderPage (/home/node/app/.next/server/pages/_document.js:85:30)
    at Function.getInitialProps (/home/node/app/.next/server/chunks/590.js:542:19)
    at Function.getInitialProps (/home/node/app/.next/server/pages/_document.js:89:85)
    at loadGetInitialProps (/home/node/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/home/node/node_modules/next/dist/next-server/server/render.js:54:1145)
```

**Comment by ma-karai** [comment]
`But it did work when i had no labels on other containers. (not that this was useful) :)`

same

**Comment by Inlustra** [comment]
Fixed in latest release on Docker apologies guys! That was a mean bug to track down.

**Comment by petersem** [comment]
looks to be working for me now. many thanks

**Comment by ma-karai** [comment]
Awesome sauce!
